USE [Position_DB]
GO
/****** Object:  Table [RWA].[SecuCCR_SVaRInfo]    Script Date: 2016/2/24 16:18:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [RWA].[SecuCCR_SVaRInfo](
	[ID] [int] NOT NULL,
	[Balance_Date] [date] NOT NULL,
	[组合序号] [int] NULL,
	[识别码] [varchar](255) NULL,
	[SVaR] [decimal](28, 10) NULL,
	[更新时间] [date] NOT NULL,
 CONSTRAINT [PK_SecuCCR_SVaRInfo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
