USE [Position_DB]
GO
/****** Object:  Table [RWA].[MKT_DATA]    Script Date: 2016/2/24 16:18:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [RWA].[MKT_DATA](
	[ID] [int] NOT NULL,
	[Code] [varchar](255) NULL,
	[Balance_Date] [date] NULL,
	[PRICE] [decimal](20, 15) NULL,
	[AssetType] [varchar](255) NULL,
 CONSTRAINT [PK_MKT_DATA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
